version: '3.8'
services:
  vprodb: 
    build: 
      context: ./Docker-files/db
    image: vprocontainers/vprofiledb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
  
  vprocache01:
    image: memcached
    container_name: vprocache01
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    container_name: vpromq01
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp: 
    build: 
     context: ./Docker-files/app
    image: vprocontainers/vprofileapp
    ports:
     - "8081:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    
  vproweb: 
    build: 
      context: ./Docker-files/web
    image: vprocontainers/vprofileweb
    ports:
      - "81:80"
    
volumes:
  vprodbdata: {}
  vproappdata: {}


     